version: '2'
services:
  redis:
      image: 'redis:3.0-alpine'
      command: redis-server --requirepass securepassword
      ports:
        - '6379:6379'
  app:
    image: keymetrics/pm2-docker-alpine
    volumes:
      - "./app:/app"
    ports:
      - "3000:3000"
    links:
      - "redis"
    command: "pm2 start ./processes.json --no-daemon"